branches:

  release: 
      Key:
      Version: '4.8.1'
      IgnoreInstalledVersion: False
      Download: https://github.com/SRMM-Studio/srmm-distrib/raw/main/ShinRyuModManager/ShinRyuModManager4.8.1.zip

  dev: 
      Key: passwardsaltsalt
      Version: '0.0.0'
      IgnoreInstalledVersion: True
      Download: 
